spring:
  application:
    name: api-server
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:sk-placeholder}
      embedding:
        options:
          model: text-embedding-3-small
      chat:
        options:
          model: gpt-5.2
          temperature: 0.7
  jpa:
    database: postgresql
    properties:
      hibernate:
        default_batch_fetch_size: 100
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

custom:
  cors:
    allowed-origins: http://localhost:8000,https://devtag.hobeenkim.com,https://www.developtag.com,https://developtag.com

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: https://qxshcgkarlmnzbkiirgo.supabase.co/auth/v1/.well-known/jwks.json
#          issuer-uri: https://qxshcgkarlmnzbkiirgo.supabase.co/auth/v1