create table category (
    name varchar(255) primary key
);

insert into category (name) values ('Java'), ('Kubenetes');

create table post (
    post_id bigint generated by default as identity primary key,
    title varchar(255),
    category varchar(255),
    description text,
    url text,
    thumbnail_url text,
    created_by varchar(255),
    created_at timestamp(6)
);