CREATE TABLE tag (
     tag_id bigint generated by default as identity primary key,,
     name VARCHAR(255) NOT NULL
);

CREATE TABLE post (
  post_id  bigint generated by default as identity primary key,,
  title VARCHAR(255) NOT NULL,
  source VARCHAR(255) NOT NULL,
  url text NOT NULL,
  pub_date timestamp(6) NOT NULL,
  description TEXT,
  thumbnail text
);

CREATE TABLE post_tag (
      post_id BIGINT NOT NULL,
      tag_id BIGINT NOT NULL,
      PRIMARY KEY (post_id, tag_id),
      FOREIGN KEY (post_id) REFERENCES post(post_id),
      FOREIGN KEY (tag_id) REFERENCES tag(tag_id)
);